backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "page" # Used in routes, e.g. /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "trainings"
    name: "trainings"
    folder: "_trainings/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Date and time", name: "datetime", widget: "datetime"}
      - {label: "Type of training", name: "type", widget: "select", options: ["webinar", "in-person", "online"]}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "flyer"
        name: "flyer"
        widget: "file"
        default: "/uploads/training/"
        media_library:
        config:
        multiple: true
      - {label: "Status", name: "status", widget: "select", options: ["live", "archived", "draft"]}
